name: Build LaTeX document for testing kanbun
on: [push]
jobs:
  build_lualatex_w_ichire:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: lualatex_w_ichire-test.tex
          latexmk_use_lualatex: true
  build_xelatex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: xelatex-test.tex
          latexmk_use_xelatex: true
